### PR TITLE
Created the ticket class and the associated controller and view code.

### PR DESCRIPTION
**Pull request by csiewecke**
Please approve ticket code.

### CODE REVIEW

**Comment by mitchcail** [comment]
looks good too me

**Comment by alhetimamoon** [comment]
Looking good, merge!

**Comment by ntartania** [comment]
You shouldn't merge code that fails CI.
The reason your CI is failing is that you didn't specify to use Ruby 2.0.
For this you need to add a circle.yml file in the root directory of your project.
See https://circleci.com/docs/configuration

**Comment by mitchcail** [comment]
your totally right. thanks for the document ill make that change now.

**Comment by ntartania** [comment]
also if your code is merged to master then let's see it deployed to production.

**Pull request merged**
